name: BlueMapCustomSkinProvider
version: ${project.version}
main: com.technicjelle.bluemapcustomskinprovider.BlueMapCustomSkinProvider
api-version: 1.13
depend:
  - BlueMap
softdepend:
  - PlaceholderAPI
authors: [ TechnicJelle ]
description: ${project.description}
website: ${project.url}
loadbefore:
  - BlueMapFloodgate
